name: fawa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy
  - scipy
  - pillow
  - opencv
  - scikit-image
  - tqdm
  - pandas
  - pip:
      - tensorflow==1.12.0
      - calamari-ocr==0.3.5
      - cleverhans==3.0.1
      - matplotlib==3.0.3
      - scikit-learn==0.21.2
      - imageio==2.5.0
      - h5py==2.9.0
      - protobuf==3.4.0
      - tqdm==4.31.1
